export const users = [
    {
      id: 1,
      first_name: "Martine",
      last_name: "Boulanger",
      bd: 8,
      bm: 12,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U022X6CCHCG-30a86c6b26f8-512",
      active: true,
      face: true,
    },
    {
      id: 2,
      first_name: "Kostiantyn",
      last_name: "Smokvina",
      bd: 11,
      bm: 10,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U03KE69T28L-cb6f298547e3-192",
      active: true,
      face: true,
    },
    {
      id: 3,
      first_name: "Nickolas",
      last_name: "Matiychenko",
      bd: 20,
      bm: 12,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCF4LUFCH-352497bed10e-512",
      active: true,
      face: false,
    },
    {
      id: 4,
      first_name: "Dmytro",
      last_name: "Makukh",
      bd: 13,
      bm: 7,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U02C3U6P946-11911193cf95-512",
      active: true,
      face: true,
    },
    {
      id: 5,
      first_name: "Olha",
      last_name: "Bobkova",
      bd: 8,
      bm: 3,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U02P2FLBRPX-eef25eeaa45e-512",
      active: true,
      face: true,
    },
    {
      id: 6,
      first_name: "Tomas",
      last_name: "Gudmundsson",
      bd: 9,
      bm: 10,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U032HTJTQSD-f332ba6232b9-192",
      active: true,
      face: false,
    },
    {
      id: 7,
      first_name: "Raf",
      last_name: "Maesen",
      bd: 11,
      bm: 9,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-URWSME3CH-5a77b883d6b8-512",
      active: true,
      face: false,
    },
    {
      id: 8,
      first_name: "Sofie",
      last_name: "Daniëls",
      bd: 28,
      bm: 8,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCE3342BZ-8af214230f7b-512",
      active: true,
      face: false,
    },
    {
      id: 9,
      first_name: "Georgia",
      last_name: "Hobbs",
      bd: 26,
      bm: 9,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U05ND2XAGF2-734d866c55b5-512",
      active: true,
      face: false,
    },
    {
      id: 10,
      first_name: "Oleksandra",
      last_name: "Romashova",
      bd: 12,
      bm: 12,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U058M72DHKQ-e99793c2a189-512",
      active: true,
      face: false,
    },
    {
      id: 11,
      first_name: "Rekha",
      last_name: "Periasamy",
      bd: 23,
      bm: 1,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U0496V421NG-5e9d06569c5c-512",
      active: true,
      face: true,
    },
    {
      id: 12,
      first_name: "David",
      last_name: "Holender",
      bd: 3,
      bm: 5,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCDFNNYQP-6464b982e140-512",
      active: true,
      face: false,
    },
    {
      id: 13,
      first_name: "Sergey",
      last_name: "Morin",
      bd: 5,
      bm: 11,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UFX4MULTC-e7ce7aee1813-512",
      active: true,
      face: false,
    },
    {
      id: 14,
      first_name: "Mart",
      last_name: "Mäe",
      bd: 1,
      bm: 2,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U02LECC2E4Q-c106dd5e6d49-512",
      active: true,
      face: false,
    },
    {
      id: 15,
      first_name: "Stanli",
      last_name: "Volmerson",
      bd: 12,
      bm: 2,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U01V6V6BS0N-b9808fbe6f06-512",
      active: true,
      face: false,
    },
    {
      id: 16,
      first_name: "Brendan",
      last_name: "Peo",
      bd: 10,
      bm: 12,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCDN6TN5V-bf457760b9df-512",
      active: true,
      face: false,
    },
    {
      id: 17,
      first_name: "Chantelle",
      last_name: "Herbst",
      bd: 22,
      bm: 11,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UDVH07HGT-4a9f0a672c5b-512",
      active: true,
      face: false,
    },
    {
      id: 18,
      first_name: "Robin",
      last_name: "Carlsson",
      bd: 12,
      bm: 4,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCDQN6CAE-f6a1b6bd484f-512",
      active: true,
      face: false,
    },
    {
      id: 19,
      first_name: "Marko",
      last_name: "Rytkönen",
      bd: 11,
      bm: 6,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-UCDV0ARL3-fd3092833886-512",
      active: true,
      face: false,
    },
    {
      id: 20,
      first_name: "Adarsh",
      last_name: "Manickam",
      bd: 1,
      bm: 9,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U02BZQ1FVAT-49cad37c1950-512",
      active: true,
      face: false,
    },
    {
      id: 21,
      name: "Ivan Skohariev",
      bd: 10,
      bm: 12,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-U0403BM2VUJ-0280cc985852-512",
      active: true,
      face: true,
    },
    {
      id: 22,
      name: "Pawel Siejba",
      bd: 12,
      bm: 1,
      photo_link:
        "https://ca.slack-edge.com/TC4562M3J-URWS4K1G9-f8daa691bbb2-512",
      active: true,
      face: true,
    },

  ]
