<template>
  <div class="page page--faq">
    <Header />
    <div class="page__content" style="width:100%">
      <h2>What is this service for?</h2>
      <p>This tool helps create fun and silly illustrations that can be used to wish Vaimo employees a happy birthday. Original idea description is <a href="https://whimsical.com/perfect-birthday-cake-ai-hackathon-ideas-Es7StfLixq4YZMhjkNo84Y" class="accent" target="_blank">here</a>.</p>

      <h2>Who can use this tool?</h2>
      <p>Initially, it is created for Vaimo HR managers who are posting birthday wishes, but each Vaimo employee at the moment can use it to create an illustration.</p>

      <h2>How can I create an illustration?</h2>
      <p>Go to <a class="accent" href="/factory">Factory</a> page, choose an employee and press "Generate" button.</p>

      <h2>I want to create an illustration with my photo, but I can't find my name in the list</h2>
      <p>You have to <a class="accent" href="https://forms.gle/PHP6S9fVBWtm49xWA" target="_blank">this form</a> to add your name into the list. It can take up to several days to appear in a list. Sorry :(</p>

      <h2>I want to create an illustration for another person, but I can't find his name in the list</h2>
      <p>Ask this person to submit <a class="accent" href="https://forms.gle/PHP6S9fVBWtm49xWA" target="_blank">this form</a> to add his name into the list.</p>

      <h2>Why there is only a cake without face for some people?</h2>
      <p>Some people forbid their photos from being used for AI processing. In these cases, we will generate only the cake image.</p>

      <h2>I have my name in the list, my there is a cake generated without my face. How to add my face?</h2>
      <p>This is because your profile is marked as "I forbid to use my photo for AI". Please <a href="/help" class="accent">contact us</a> to change this setting.</p>

      <h2>Can I create an illustration for a friend of family member who does not work at Vaimo?</h2>
      <p>Not at the moment, but we expect to provide this opportunity soon.</p>

      <h2>Generated illustration is ugly, offensive, racist or just does not look like the original person!</h2>
      <p>First of all, please understand that this service is created to bring joy (initial intent). We do not intend to offend or insult anyone in any way. However, since the technical essence of the service consists in creating a cartoon illustration based on a photograph (and due to the fact we do not control the results as they are generated by third-party AI service), some facial features, body characteristics, nationality characteristics or other details in the process of generation may be hyperbolized, which can lead to unexpected results.</p>
      <p>If you are not satisfied with any of the generated results, please try to generate again - each time they are slightly different. This can also help if the first results do not resemble the desired person. Also, please note that illustrations are generated based on photos of the user set in Slack, hiBob or WorkPlace. If the face is poorly visible in the photo, if the photo is of poor quality or if the photo is outdated - the results are more likely to differ from the person you know personally.</p>

      <h2>I don't wont my photos to be used in this service!</h2>
      <p>If you do not want your photo to be used for generations - please check your name in the list on "Factory page". If your name is not present in the list or your name is marked with a 🎂 "cake" icon - nobody will be able to create illustration based on your photo within this service. If there is a 👤 "person" icon next to your name - please <a href="/help" class="accent">contact us</a> to fix this.</p>

    </div>
    <Footer />
  </div>
</template>

<script>
import LoginForm from '../components/Forms/LoginForm.vue';
import Footer from '../components/Footer/Footer.vue';
import Header from '../components/Header/Header.vue';

export default {
  name: 'FAQPage',
  components: { LoginForm, Footer, Header },
}
</script>

<styles lang="css" scoped>
</styles>
